"""add media variants

Revision ID: 4d36dea2c925
Revises: d3a7e69d727b
Create Date: 2026-08-04 15:50:03.975652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d36dea2c925'
down_revision = 'd3a7e69d727b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('variants', sa.JSON(), nullable=True))

    op.execute(sa.text("UPDATE media_assets SET sha256 = '' WHERE sha256 IS NULL"))
    op.execute(sa.text("UPDATE media_assets SET variants = '{}' WHERE variants IS NULL"))

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.alter_column('sha256', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('variants', existing_type=sa.JSON(), nullable=False)
        batch_op.create_index(batch_op.f('ix_media_assets_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_sha256'))
        batch_op.drop_column('variants')
        batch_op.drop_column('sha256')

    # ### end Alembic commands ###
